// Package api_gateway Code generated by swaggo/swag. DO NOT EDIT
package api_gateway

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Serves main search page",
                "tags": [
                    "web"
                ],
                "summary": "Web service proxy",
                "responses": {}
            }
        },
        "/chat/{id}": {
            "get": {
                "description": "Proxies chat-related requests (chats, messages, groups)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Chat service proxy",
                "responses": {}
            }
        },
        "/group-chat/create": {
            "get": {
                "description": "Proxies chat-related requests (chats, messages, groups)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Chat service proxy",
                "responses": {}
            },
            "post": {
                "description": "Proxies chat-related requests (chats, messages, groups)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Chat service proxy",
                "responses": {}
            }
        },
        "/group-chat/join-to-chat/{groupID}": {
            "get": {
                "description": "Proxies chat-related requests (chats, messages, groups)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Chat service proxy",
                "responses": {}
            }
        },
        "/login": {
            "get": {
                "description": "Proxies user-related requests (login, register, search)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "User service proxy",
                "responses": {}
            },
            "post": {
                "description": "Proxies user-related requests (login, register, search)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "User service proxy",
                "responses": {}
            }
        },
        "/my-chats": {
            "get": {
                "description": "Proxies chat-related requests (chats, messages, groups)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Chat service proxy",
                "responses": {}
            }
        },
        "/register": {
            "get": {
                "description": "Proxies user-related requests (login, register, search)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "User service proxy",
                "responses": {}
            },
            "post": {
                "description": "Proxies user-related requests (login, register, search)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "User service proxy",
                "responses": {}
            }
        },
        "/search/{username}": {
            "get": {
                "description": "Proxies user-related requests (login, register, search)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "User service proxy",
                "responses": {}
            }
        },
        "/start-chat/{userID}": {
            "get": {
                "description": "Proxies chat-related requests (chats, messages, groups)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Chat service proxy",
                "responses": {}
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "jwt",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "FCH API",
	Description:      "API Gateway for FCH messenger. All protected routes require JWT cookie.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
